default_platform(:android)
 
platform :android do 
  desc "Deploy a new version to Release"
  lane :release do
    upload_to_play_store(
      aab: "../build/app/outputs/bundle/release/app-release.aab",
      track: "alpha",
      rollout: "1",
      skip_upload_screenshots: true
    )
  end
end